server:
  port: 8762

spring:
  application:
    name: zuul-server
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_list?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    showSql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    security:
      path: /security/**
      serviceId: security-service
    gallery:
      path: /gallery/**
      serviceId: gallery-service

endpoints:
  routes:
    sensitive: false









